### ISSUE TITLE
Banner blocks view of navbar

### ISSUE THREAD

**Issue by pistachiosgreen** [BranchMetrics/web-branch-deep-linking#342]
Hi,

Is there a way to put the banner above the navbar? 

I tried changing the position of the navbar (top:100px). However, then if I were to close the smart banner, the navbar remains in the same position and blocks other elements on the page. Am I supposed to use an event listener so that when the smart banner is closed I move the navbar back to the top (top:0px) ? 

Do you guys provide a better alternative?

Thanks!

**Comment by jsaleigh** [comment]
Hi @pistachiosgreen!

Do you have a live example to take a look at?  The banner should push your navigation bar down in most cases, but we have seen instances where hosted CSS causes issues that prevents this.

Alternatively, as you suggested there are a set of events that can be listened to, so that site adjustments can be made: https://github.com/BranchMetrics/web-branch-deep-linking#addlistenerevent-listener

Hope this helps!

**Comment by pistachiosgreen** [comment]
I do, but not sure if I'm allowed to post up the live site yet. Anyhow, yes the banner isn't pushing down the navigation bar so I guess the only solution is to use event listeners to manually change the position of the navigation bar.

Thanks for your help!
