### ISSUE TITLE
Reinit with new options

### ISSUE THREAD

**Issue by jaybekster** [BranchMetrics/web-branch-deep-linking#349]
Hello.
Can I init banner again wtih new options, especially texts, without deleting previous one? It must change texts in some cases while it has been shown already, but no way...

**Comment by jsaleigh** [comment]
Hi @jaybekster.  Yes, each call to branch.banner() should use your most recent changes.  Is this not working for you?

**Comment by yntema** [comment]
If an existing banner is showing, we will not show a new one until the existing one has been closed or a new page has been rendered. In order to resolve this, please update to use Journeys instead of the legacy smartbanner. Using Journeys, you have the ability to close a banner and rerender another. Learn more about Journeys here: https://docs.branch.io/pages/web/journeys/
