### ISSUE TITLE
didDownloadApp - event emitted from ```branch.banner({})```

### ISSUE THREAD

**Issue by Jusdev89** [BranchMetrics/web-branch-deep-linking#449]
when I implement a ```branch.addListenter(event, listener)```, does the "didDownloadApp" event only fire when the app is downloaded in the store or does it fire when the button is clicked??

**Comment by yntema** [comment]
Hi @Jusdev89 , this is a great question. Once we recognize that a user has downloaded the app, the next time they visit the website, we will fire this event. This event coincides with an update to session data indicating that a user has installed the app.

- The reason we don't fire the event when the app is downloaded in the store is because the use may not be on the website anymore and we also may not know about the download immediately.
- The reason we don't fire this event when the button is clicked, is we can't make any guarantee that they will follow through with a download.

Hopefully this was helpful. Let me know if this is still unclear.

**Comment by Jusdev89** [comment]
Thanks alot @yntema for the clarity. This is closed for me.
