### ISSUE TITLE
Branch.io swallows errors in the success callback

### ISSUE THREAD

**Issue by saivann** [BranchMetrics/web-branch-deep-linking#456]
I appears that the branch.io SDK swallows errors. Likely as a result of using a promise `.catch()` statement that does not throw any error.

In my case, this led to swallowing errors in much larger parts of the codebase, running as a side effect of the success callback. This may also be the case for other users.

A real example of a swallowed error:

```
function success() {
    throw new Error('test'); <----------- This never prints in the console
}

branch.init(key, success);
```

And a workaround to escape the promise `.catch()` statement with `setTimeout`

```
function success() {
    throw new Error('test'); <----------- This prints in the console as expected
}

function wrap(...args) {
    setTimeout(() => success(...args));
}

branch.init(key, wrap);
```

Thanks for making our life easier with branch.io! Really like the library :-)

**Comment by jsaleigh** [comment]
@saivann Hmm, that is possible, but shouldn't be happening.  I'll start up an internal ticket, and see if we can get a better solution available for you.  Thanks for reporting this :)

**Comment by jsaleigh** [comment]
Hey @saivann, after talking with the team on this one, it looks like I was wrong, and this is actually the intended behavior.  Essentially, we are attempting to prevent the failure of the `branch.init` call due to any potential errors within that callback, or the passing of errors from within the callback back out to the top level code where it would be harder to debug through due to the minimized SDK code.

If the WebSDK encounters an error during initialization, then that will appear in the err parameter of the callback. But if you want to throw your own error inside that callback, then wrap that functionality with a try/catch block, within the callback itself.  We cannot pass that error back up the chain.

The history behind this was that we had partners who threw errors in their callbacks, which caused `branch.init` to fail because of that. Since the crash happened in the `branch.init` calls, it looked like we were breaking their sites, which delayed them from being able to find the real cause.  Handling errors this way was meant to help with debugging processes in general, so I'm sorry to hear that it slowed yours down.

Hope this helps :)

**Comment by saivann** [comment]
Hey, thanks for following up.

This being said, you may want to keep this in mind; Anything that runs as side effect of branch.io.init cannot throw errors as a result of that condition. This can propagate to silencing errors in large parts of an app that are largely unrelated to branch.io (in my case it was a full page due to React sync rendering).

Reading your comment here:
> Since the crash happened in the branch.init calls, it looked like we were breaking their sites

I am wondering if the root issue was branch.init throwing a newly generated errors (which would indeed generate a stack trace pointing at branch.io's code), as opposed to just throwing the existing error (which would display a stack trace pointing at the actual bug in your user's code).

I know for a fact that differenciating errors in promises can be tricky. In case the above is accurate, and that is of any help to you, one useful trick is to have all errors from your library be instances of the same custom error class generated by your library. This way you can differenciate errors in your own code from errors in your customer's code with the use of `instanceof`.

Either way, thanks again for following up and for branch.io :) . The existing workaround I am using is working just fine for me.
