### ISSUE TITLE
CORS issue

### ISSUE THREAD

**Issue by sebasnavarrete** [BranchMetrics/web-branch-deep-linking#465]
Some days ago, our users report problems with the branch links, when we check the issue, we could identify that we are presenting a problem of 'CORS' that was not presented before, no changes have been generated in the site.

We use branch some months ago without any trouble, but this new issue is terrible for our application performance.
Thank you for your prompt cooperation.

This is the browser console message:
[Error] Origin https://w.pingpro.com is not allowed by Access-Control-Allow-Origin.
[Error] Failed to load resource: Origin https://w.pingpro.com is not allowed by Access-Control-Allow-Origin. (open, line 0)
[Error] XMLHttpRequest cannot load https://api.branch.io/v1/open due to access control checks.

**Comment by donedgardo** [comment]
Having same issue locally and on production server 
```
(index):1 XMLHttpRequest cannot load https://api.branch.io/v1/open. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access. The response had HTTP status code 400.
```

**Comment by rubinsingh** [comment]
@sebasnavarrete if this is still an issue, please feel free to email integrations@branch.io with a few more details about your app and we'd be glad to assist. 

@donedgardo I believe your issue was addressed by Jackie of our integrations team. Feel free to reply to that email if you are still experiencing the issue or have any further concerns.
