### ISSUE TITLE
SendSMS doesn't work in provided example

### ISSUE THREAD

**Issue by mikhailmelnik** [BranchMetrics/web-branch-deep-linking#483]
I'm trying to implement Desktop SMS and run into the issue which I was able to replicate on the example page from documentation: https://cdn.branch.io/example.html. When I click SendSMS it gets failed with the following error in console:

![error](https://user-images.githubusercontent.com/3161857/29037767-6b59ef26-7be8-11e7-8e4a-36505e4df1c4.PNG)

**Comment by mikhailmelnik** [comment]
Just realized the page in response (which confused me a lot but seems to be not a source of issue) reports an invalid phone number. I was trying to use my Australian number, do you have any restriction on this? Does this restriction (if any) applies to the country or related to the billing?

**Comment by mikhailmelnik** [comment]
Just worked out this issue a little bit more. It turned out this page works perfectly for my colleagues in Australia for Australian numbers but doesn't for UAE of Thai numbers. In Thailand it works for Thai numbers only but doesn't work for Australian or UAE. It there any restriction that you should use only numbers for the country you are in?

**Comment by rubinsingh** [comment]
Hey @mikhailmelnik , I'm sorry to hear you're running into issues with this. We've recently had to implement stricter rules on SMS requests, due to a increase in spam. As such, attempting to send to a number from outside it's country of origin may result in an error message. So long as you are sending to a number in the same country as you, you should not get any errors. The current error message being returned is a generic response, but we are looking at options to make this more descriptive.

**Comment by rubinsingh** [comment]
@mikhailmelnik feel free to reach out to integrations@branch.io if you've got more questions about this.
