### ISSUE TITLE
What script should I include?

### ISSUE THREAD

**Issue by cloud-walker** [BranchMetrics/web-branch-deep-linking#526]
This: https://github.com/BranchMetrics/web-branch-deep-linking#recommended-installation

or this? https://github.com/BranchMetrics/web-branch-deep-linking/blob/master/dist/build.min.js

I prefer to use the npm one, but its 60KB vs 600bytes of the one in the readme!!

**Comment by rubinsingh** [comment]
@cloud-walker apologies for the delay in responding! For any general questions, integrations@branch.io is the fastest way to reach out for help. 

Going back to your question, my recommendation is to use the recommended installation instructions found at:

`https://github.com/BranchMetrics/web-branch-deep-linking#recommended-installation
`
This is the path that most of our partners choose when integrating the WebSDK into their sites. If you choose to go the npm module route, the file that you would want to import is the dist/build.min.js. With regards to the size, the difference is due to the minified file on our cdn being compressed and gzipped. 

I hope this helps! Feel free to reach out to integrations@branch.io for any further questions or concerns.
