### ISSUE TITLE
Security, SMS sending

### ISSUE THREAD

**Issue by finnhvman** [BranchMetrics/web-branch-deep-linking#534]
When I'm using the branch SDK on the client side, what prevents a malicious attacker from stealing my Branch key, and use it to send texts, even with arbitrary messages?

Is there a way to restrict API calls, maybe restricting based on `Origin` header?

**Comment by snakingfire** [comment]
Hey @finnhvman, great question!

Because of the way that Text-Me-The-App is designed to function (an arbitrary, unauthenticated user must be able to make the request to send an SMS message) there isn't anything directly stopping an attacker from using your Branch key to send a message, since restricting in this way has the potential to block legitimate users from using the feature. 

Your suggestion of an Origin header check would work well for assuring that a message was actually sent from your domain (preventing CSRF), but there are still ways for an attacker to get around this (eg, they could visit your site and manually send messages). Because of this, we focus primarily on preventing the ability for a TMTA link to be used maliciously, even if it is delivered to a user's device, as well as methods of detecting and blocking illegitimate traffic (for obvious reasons, I can't go into much detail on this part).

Above said, if you have any specific concerns, please don't hesitate to reach out to security@branch.io. 

Happy Deep Linking!
